services:

  ai-service-backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    container_name: ai-service-backend
    restart: unless-stopped
    depends_on:
      - ai-model
    ports:
      - "8080:8080"
    networks:
      - ai_network

  ai-service-frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    container_name: ai-service-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - ai_network
    depends_on:
      - ai-service-backend

  ai-model:
    build:
      context: ./ai_model
      dockerfile: dockerfile.ai
    container_name: ai-model
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge