FROM maven:3.9.9-amazoncorretto-21 AS build
COPY pom.xml ./
RUN mvn dependency:go-offline -B
COPY . ./
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY --from=build target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]